- hosts: test1app03.proxibid.com

 tasks:
  - name: connect to appserver
    shell: sshpass -p password ssh -T ansible-user@test1app03.proxibid.com
	become: yes
	
  - name: root to user
    shell: sudo su proxibid
	become: yes	
 
  - copy:
	src: /tmp/copysachi
	dest: /opt/proxibid/jetty/9.3/webapps
	owner:proxibid
	mode: 0777 
	